server:
 port: 9090

spring:
 aplication:
  name: msvc-course
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/microservice_courses
  username: postgres
  password: 12345
 jpa:
  hibernate:
   ddl-auto: create
   database: postgresql
   database-plataform: org.hibernate.dialect.PostgreSQLDialect
 config:
   import: optional:configserver:http://localhost:8888

eureka:
 instance:
  hostname: localhost
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka